# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
    env_file:
      - .env
    environment:
      - NODE_ENV:production
#      - DATABASE_URL:"postgresql://postgres:root@db:5432/tahsin?schema=public"
      - DATABASE_URL:"postgresql://neondb_owner:C4YmONXk8lgu@ep-lucky-cloud-a5lw4zdy-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require"
    ports:
      - 5000:5000
#    depends_on:
#      db:
#        condition: service_healthy

#  db:
#    image: postgres
#    restart: always
#    user: postgres
#    secrets:
#      - db-password
#    volumes:
#      - db-data:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_DB:tahsin
#      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#    expose:
#      - 5433:5432
#    healthcheck:
#      test: ["CMD", "pg_isready"]
#      interval: 10s
#      retries: 5

#volumes:
#  db-data:
#
#secrets:
#  db-password:
#    file: db/password.txt