export const USER_REPO_TOKEN = 'USER_REPO_TOKEN';
export const ROLE_REPO_TOKEN = 'ROLE_REPO_TOKEN';
export const PROFILE_REPO_TOKEN = 'PROFILE_REPO_TOKEN';
export const TEACHER_REPO_TOKEN = 'TEACHER_REPO_TOKEN';
export const LEVEL_REPO_TOKEN = 'LEVEL_REPO_TOKEN';
export const EVENT_REPO_TOKEN = 'EVENT_REPO_TOKEN';
export const COMPONENT_REPO_TOKEN = 'COMPONENT_REPO_TOKEN';
export const TIME_REPO_TOKEN = 'TIME_REPO_TOKEN';
export const DAY_REPO_TOKEN = 'DAY_REPO_TOKEN';
export const BANK_ACCOUNT_REPO_TOKEN = 'BANK_ACCOUNT_REPO_TOKEN';
export const COURSE_FEE_REPO_TOKEN = 'COURSE_FEE_REPO_TOKEN';
export const SCHEDULE_REPO_TOKEN = 'SCHEDULE_REPO_TOKEN';
export const ACADEMIC_TERMS_REPO_TOKEN = 'ACADEMIC_TERMS_REPO_TOKEN';
export const ACADEMIC_CALENDER_REPO_TOKEN = 'ACADEMIC_CALENDER_REPO_TOKEN';
export const CLASS_REPO_TOKEN = 'CLASS_REPO_TOKEN';
export const ACADEMIC_TERM_PAYMENT_FEE_REPO_TOKEN =
  'ACADEMIC_TERM_PAYMENT_FEE_REPO_TOKEN';
export const REGISTRATION_REPO_TOKEN = 'REGISTRATION_REPO_TOKEN';
export const PAYMENT_CONFIRMATION_REPO_TOKEN =
  'PAYMENT_CONFIRMATION_REPO_TOKEN';
